[package]
name = "DvoRAKU-JIS"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
windows = { version = "0.60.0", features = ["Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
